### PR TITLE
Fixed infinite redirects when trying to GET an Instagram profile

### LINKED ISSUE #32: Proxy silently fails when trying to open an instagram profile because of a cookie host mismatch error
**Steps to reproduce:**
1. Use this package to proxy a **request** to https://instagram.com/nike 

**Expected result:** The profile loads, or a login form shows up if the proxy server is not trusted by Instagram

**Actual result:** The proxy package never resolves the request. It just fails silently. 

**Solution:** Turns our it was a cookie host mismatch error that was being caught by the package. I fixed this issue by adding `ignoreInvalidCookies: true` to `got`'s `options` in [proxy.js](https://github.com/Cuadrix/puppeteer-page-proxy/blob/47358301a1366389315dcfc9cfc34b45430d3bf6/src/core/proxy.js#L22).

---
But now I have a different issue: Instagram keeps redirecting me to the same URL. The redirect is client-side, so it happens infinitely. 

This issue does NOT happen when I use the proxy-server arg with Puppeteer, so it must have something to do with this package.

I suspect it has something to do with how this package handle cookies.

I'll update this issue as I investigate this further. Just wanted to post here so others don't waste hours getting this far like I did.

### PR DESCRIPTION
**Pull request by ardalann**
Closes #32 

Fixed bugs:
- Silent failure when there was an invalid host in the cookies set by the server
- Page URL not updating in Puppeteer when there was a server-side redirect (via location header)

Improvements:
- Added an optional `ignoreInvalidCookies` option to make this change backwards-compatible
- Added a `.gitignore` file so `/node_modules` cannot be committed to the repo
- Added a `throw error;` so that useProxy does not fail silently when there is an error. This error can be caught by the consumer if they want to ignore it or handle it. This is NOT a backwards-compatible change.

### CODE REVIEW

File: src/core/proxy.js [hunk 1]
```diff
@@ -35,7 +40,10 @@ const requestHandler = async (request, proxy, overrides = {}) => {
             headers: response.headers,
             body: response.body
         });
-    } catch(error) {await request.abort()}
```
Comment (Cuadrix) [inline src/core/proxy.js:38]: Use `} catch(error) {await request.abort()}` instead

File: src/core/proxy.js [hunk 2]
```diff
@@ -19,7 +19,12 @@ const requestHandler = async (request, proxy, overrides = {}) => {
         agent: setAgent(proxy),
         responseType: "buffer",
         maxRedirects: 15,
-        throwHttpErrors: false
+        throwHttpErrors: false,
+        ignoreInvalidCookies:
```
Comment (Cuadrix) [inline src/core/proxy.js:23]: `ignoreInvalidCookies: true,`

File: README.md [hunk 3]
```diff
@@ -21,7 +21,7 @@ npm i puppeteer-page-proxy
 - `proxy` <[string](https://developer.mozilla.org/en-US/docs/Glossary/String)|[object](https://developer.mozilla.org/en-US/docs/Glossary/Object)> Proxy to use in the current page.
   * Begins with a protocol (e.g. http://, https://, socks://)
   * In the case of [proxy per request](https://github.com/Cuadrix/puppeteer-page-proxy#proxy-per-request), this can be an object with optional properties for overriding requests:\
-`url`, `method`, `postData`, `headers`\
+`url`, `method`, `postData`, `headers`, `ignoreInvalidCookies`\
```
Comment (Cuadrix) [inline README.md:24]: Is `ignoreInvalidCookies` really necessary?

File: src/core/proxy.js [hunk 4]
```diff
@@ -19,7 +19,12 @@ const requestHandler = async (request, proxy, overrides = {}) => {
...
+            typeof overrides.ignoreInvalidCookies === "undefined"
+                ? false
+                : overrides.ignoreInvalidCookies,
+        followRedirect: false
```
Comment (Cuadrix) [inline src/core/proxy.js:27]: Remove the conditional and just use `ignoreInvalidCookies: true,`

File: src/core/proxy.js [hunk 5]
```diff
@@ -35,7 +40,10 @@ const requestHandler = async (request, proxy, overrides = {}) => {
             headers: response.headers,
             body: response.body
         });
-    } catch(error) {await request.abort()}
+    } catch (error) {
+        await request.abort();
+        throw error;
+    }
```
Comment (Cuadrix) [inline src/core/proxy.js:46]: Use `} catch(error) {await request.abort()}` instead (?)

File: src/core/proxy.js [hunk 6]
```diff
@@ -19,7 +19,12 @@ const requestHandler = async (request, proxy, overrides = {}) => {
         agent: setAgent(proxy),
         responseType: "buffer",
         maxRedirects: 15,
-        throwHttpErrors: false
+        throwHttpErrors: false,
+        ignoreInvalidCookies:
+            typeof overrides.ignoreInvalidCookies === "undefined"
+                ? false
+                : overrides.ignoreInvalidCookies,
```
Comment (Cuadrix) [inline src/core/proxy.js:26]: Remove the conditional and just use `ignoreInvalidCookies: true,`

File: README.md (hunk 3 above)
Comment (ardalann) [reply README.md:24]: I wouldn't mind setting it to true by default and not having it as an option, but I thought you may like it this way. I'll change it then.

File: src/core/proxy.js (hunk 5 above)
Comment (ardalann) [reply src/core/proxy.js:46]: Ah I see. I'll revert it then.

File: src/core/proxy.js (hunk 6 above)
Comment (ardalann) [reply src/core/proxy.js:26]: Sounds good 👍

**Comment by ardalann** [comment]
@Caudrix I just updated the PR.

**Comment by Cuadrix** [comment]
Thanks for contributing ^

**Comment by ardalann** [comment]
@Cuadrix no worries. Thanks for the great npm package!
Are you going to publish a new version right away?

**Comment by Cuadrix** [comment]
Yes, just a couple minutes and it should be out
